---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "The Lab"
subtitle: " "
logo: "assets/tools/lablogo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false
#footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
#message:
  #url: https://b4bz.io
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/Harrison-S1"
    target: "_blank" # optional html a tag target attribute
  - name: "Cloud Guru"
    icon: "fas fa-cloud"
    url: "https://learn.acloud.guru/dashboard"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
  - name: "Duck DNS"
    icon: "fab fa-earlybirds"
    url: "https://www.duckdns.org/" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Servers"
    icon: "fas fa-server"
    items:
      - name: "Truenas"
        logo: "assets/tools/logo-TrueNAS-Core_119b-compressor.png"
        subtitle: "storage"
        tag: "server"
        url: "http://192.168.0.50"
        target: "_blank" # optional html a tag target attribute
      - name: "Proxmox"
        logo: "assets/tools/proxmox-logo.png"
        subtitle: "vms"
        tag: "server"
        url: "https://192.168.0.19:8006/#v1:0:=node%2Fmadhatter:4:::::::"
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "containers"
        tag: "server"
        url: "http://192.168.0.107:9000/#!/home"
  - name: "Apps"
    icon: "fas fa-cloud"
    items:
      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "moves"
        tag: "app"
        url: "https://app.plex.tv/desktop#"
      - name: "Pihole"
        logo: "assets/tools/Pi-hole_Logo.png"
        subtitle: "DNS"
        tag: "app"
        url: "http://192.168.0.107/admin/"
        target: "_blank" # optional html a tag target attribute
      - name: "Calibre-Web"
        logo: "assets/tools/calibre-web_155568.png"
        subtitle: "books"
        tag: "app"
        url: "http://192.168.0.107:8083/page/3"
      - name: "Zabbix"
        logo: "assets/tools/zabbix_logo_500x131.png"
        subtitle: "monitoring"
        tag: "app"
        url: "http://192.168.0.149/zabbix/zabbix.php?action=dashboard.view"
      - name: "SyncThing"
        logo: "assets/tools/sync.png"
        tag: "app"
        url: "http://192.168.0.103/syncthing/#"
      - name: "BookStack"
        logo: "assets/tools/bookstack.png"
        tag: "app"
        url: "http://192.168.0.107:6875/login"
  
  - name: "Network"
    icon: "fas fa-network-wired"
    items:
      - name: "Router"
        logo: "assets/tools/1200px-Router_symbol-Blue.svg.png"
        subtitle: "router"
        tag: "network"
        url: "http://192.168.0.1"
      - name: "Netbox"
        logo: "assets/tools/netbox.png"
        subtitle: ""
        tag: "app"
        url: "netbox.lol"
      - name: "Smoke Ping"
        logo: "assets/tools/smokeping.png"
        subtitle: "" 
        tag: "network"
        url: "http://192.168.0.107:8840"

  - name: "Learning"
    icon: "fas fa-chalkboard"
    items:
      - name: "Cloud Guru"
        logo: "assets/tools/cloudg.jpeg"
        subtitle: "Cloud Guru"
        tag: "tech"
        url: "https://acloudguru.com/"
      - name: "Leanpub"
        logo: "assets/tools/leanpub.png"
        subtitle: "Leanpub"
        tag: "tech"
        url: "https://leanpub.com/user_dashboard/library"
